# Generated by Django 6.0.5 on 2026-05-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dissers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('intro', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archetype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roast', to='dissers.targetarchetype')),
            ],
            options={
                'verbose_name': 'Roast',
                'verbose_name_plural': 'Roasts',
                'ordering': ['-created_on'],
            },
        ),
    ]
