# Generated by Django 6.0.5 on 2026-06-19 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('general', 'General enquiry'), ('account', 'Account issue'), ('packs', 'Packs / orders'), ('payment', 'Payment problem'), ('bug', 'Bug report'), ('safety', 'Safety / moderation'), ('collab', 'Collab / business'), ('other', 'Something weird')], default='general', max_length=30)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_on'],
            },
        ),
    ]
