# Generated by Django 6.0.5 on 2026-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoastStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('example_line', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='roast_styles/')),
            ],
            options={
                'verbose_name': 'Roast Style',
                'verbose_name_plural': 'Roast Styles',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TargetArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Target Archetype',
                'verbose_name_plural': 'Target Archetypes',
                'ordering': ['display_order'],
            },
        ),
    ]
