# Generated by Django 6.0.5 on 2026-05-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Roast Category',
                'verbose_name_plural': 'Roast Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='targetarchetype',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='archetypes/'),
        ),
        migrations.AddField(
            model_name='targetarchetype',
            name='catchphrase',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='targetarchetype',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('mid', 'Mid'), ('hard', 'Hard'), ('legendary', 'Legendary')], default='mid', max_length=20),
        ),
        migrations.AddField(
            model_name='targetarchetype',
            name='traits',
            field=models.TextField(blank=True, help_text='One trait per line'),
        ),
        migrations.AddField(
            model_name='targetarchetype',
            name='weaknesses',
            field=models.TextField(blank=True, help_text='One weakness per line'),
        ),
    ]
