# Generated by Django 6.0.5 on 2026-05-26 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0002_roastcategory_targetarchetype_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetarchetype',
            name='catchphrase',
            field=models.CharField(blank=True, help_text="e.g. 'Per my last email...'", max_length=200),
        ),
        migrations.CreateModel(
            name='Disser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='disser_avatars/')),
                ('burns_deployed', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('favourite_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='dissers.roaststyle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disser_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disser',
                'verbose_name_plural': 'Dissers',
            },
        ),
    ]
