# Generated by Django 6.0.5 on 2026-05-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0004_add_is_free_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roaststyle',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Available to free-tier users.'),
        ),
        migrations.AlterField(
            model_name='targetarchetype',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Available to free-tier users.'),
        ),
    ]
