# Generated by Django 6.0.5 on 2026-06-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0005_alter_roaststyle_is_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roastcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roastcategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='roastcategory',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Always visible to free tier users'),
        ),
        migrations.AddField(
            model_name='roastcategory',
            name='required_pack_level',
            field=models.IntegerField(default=0, help_text='0=free, 1=Diss Pack+, 2=Burn Pack only'),
        ),
    ]
