# Generated by Django 6.0.5 on 2026-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0006_remove_roastcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetarchetype',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text='Groups archetypes in the Build Your Diss carousel', max_length=1),
        ),
    ]
