# Generated by Django 6.0.5 on 2026-06-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0007_targetarchetype_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaststyle',
            name='unlock_priority',
            field=models.PositiveIntegerField(default=0, help_text="Controls which styles count as 'first' when a pack's roast_style_count determines what's unlocked. Fully independent of Display Order — change this freely to control pack tiering without disturbing the picker grid's visual layout."),
        ),
        migrations.AddField(
            model_name='targetarchetype',
            name='unlock_priority',
            field=models.PositiveIntegerField(default=0, help_text="Controls which archetypes count as 'first' when a pack's archetype_count determines what's unlocked. Fully independent of Display Order — change this freely to control pack tiering without disturbing the carousel's visual layout."),
        ),
        migrations.AlterField(
            model_name='roaststyle',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls VISUAL layout position only — e.g. the order styles appear in the Step 2 picker grid. Has no effect on which pack unlocks which style — see Unlock Priority.'),
        ),
        migrations.AlterField(
            model_name='targetarchetype',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls VISUAL layout position only — e.g. the order archetypes appear in the Step 1 carousel within their gender row. Has no effect on which pack unlocks which archetype — see Unlock Priority.'),
        ),
    ]
