# Generated by Django 6.0.5 on 2026-05-20 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dissers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('context_notes', models.TextField(blank=True, help_text='Any extra context about the target')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('commissioned', 'Commissioned'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='If true, appears on the Roast Feed')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disses', to=settings.AUTH_USER_MODEL)),
                ('roast_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissers.roaststyle')),
                ('target_archetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissers.targetarchetype')),
            ],
            options={
                'verbose_name': 'Diss',
                'verbose_name_plural': 'Disses',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='DissLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opener', models.CharField(blank=True, help_text="e.g. 'Historians will note that...'", max_length=200)),
                ('trait', models.CharField(blank=True, help_text="e.g. 'you schedule meetings like'", max_length=200)),
                ('ending', models.CharField(blank=True, help_text="e.g. 'a raccoon trapped in Outlook'", max_length=200)),
                ('full_line', models.TextField(blank=True, help_text='Or write the full line directly')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('diss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='disses.diss')),
            ],
            options={
                'verbose_name': 'Diss Line',
                'verbose_name_plural': 'Diss Lines',
                'ordering': ['display_order'],
            },
        ),
    ]
