# Generated by Django 6.0.5 on 2026-05-20 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0002_roastcategory_targetarchetype_avatar_and_more'),
        ('disses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissline',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissers.roastcategory'),
        ),
    ]
