# Generated by Django 6.0.5 on 2026-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disses', '0003_rebuild_dissline_update_diss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diss',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
