# Generated by Django 6.0.5 on 2026-05-29 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0005_alter_roaststyle_is_free_and_more'),
        ('disses', '0004_alter_diss_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dissline',
            options={'ordering': ['category', 'display_order'], 'verbose_name': 'Diss Line', 'verbose_name_plural': 'Diss Lines'},
        ),
        migrations.RemoveField(
            model_name='dissline',
            name='archetype',
        ),
        migrations.RemoveField(
            model_name='dissline',
            name='line_type',
        ),
        migrations.RemoveField(
            model_name='dissline',
            name='roast_style',
        ),
        migrations.AddField(
            model_name='dissline',
            name='archetypes',
            field=models.ManyToManyField(blank=True, related_name='diss_lines', to='dissers.targetarchetype'),
        ),
        migrations.AddField(
            model_name='dissline',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diss_lines', to='dissers.roastcategory'),
        ),
        migrations.AddField(
            model_name='dissline',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Available to free-tier users.'),
        ),
        migrations.AddField(
            model_name='dissline',
            name='roast_styles',
            field=models.ManyToManyField(blank=True, related_name='diss_lines', to='dissers.roaststyle'),
        ),
    ]
