# Generated by Django 6.0.5 on 2026-05-30 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0005_alter_roaststyle_is_free_and_more'),
        ('disses', '0005_alter_dissline_options_remove_dissline_archetype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dissline',
            options={'ordering': ['archetype', 'roast_style', 'display_order'], 'verbose_name': 'Diss Line', 'verbose_name_plural': 'Diss Lines'},
        ),
        migrations.RemoveField(
            model_name='dissline',
            name='archetypes',
        ),
        migrations.RemoveField(
            model_name='dissline',
            name='roast_styles',
        ),
        migrations.AddField(
            model_name='dissline',
            name='archetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diss_lines', to='dissers.targetarchetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dissline',
            name='roast_style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diss_lines', to='dissers.roaststyle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dissline',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dissline',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_lines', to=settings.AUTH_USER_MODEL),
        ),
    ]
