# Generated by Django 6.0.5 on 2026-06-18 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissers', '0007_targetarchetype_gender'),
        ('disses', '0006_alter_dissline_options_remove_dissline_archetypes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumDissLine',
            fields=[
            ],
            options={
                'verbose_name': 'Premium Diss Line',
                'verbose_name_plural': 'Premium Diss Lines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('disses.dissline',),
        ),
        migrations.AlterField(
            model_name='dissline',
            name='roast_style',
            field=models.ForeignKey(blank=True, help_text='Required for standard Diss Lines. Leave blank for Premium lines (LinkedIn Endorsement, Internal Monologue, etc.) — these apply to any roast style.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diss_lines', to='dissers.roaststyle'),
        ),
    ]
