# Generated by Django 6.0.5 on 2026-06-06 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='diss_count',
        ),
        migrations.RemoveField(
            model_name='package',
            name='includes_linkedin',
        ),
        migrations.RemoveField(
            model_name='package',
            name='includes_pdf',
        ),
        migrations.RemoveField(
            model_name='package',
            name='includes_performance_review',
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='gifted_to',
            field=models.ForeignKey(blank=True, help_text='If purchased as a gift for another user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifted_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='archetype_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='package',
            name='deploy_burn_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_leaderboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='premium_category_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='riposte_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='roast_style_count',
            field=models.IntegerField(default=2),
        ),
    ]
