# Generated by Django 6.0.5 on 2026-06-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_package_diss_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_line_selections',
            field=models.IntegerField(default=3, help_text='Max disslines user can select (free=1, Diss=2, Burn=3)'),
        ),
    ]
