# Generated by Django 6.0.5 on 2026-06-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_package_max_line_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='premium_diss_line_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of premium diss lines selectable per burn.'),
        ),
        migrations.AddField(
            model_name='package',
            name='standard_diss_line_count',
            field=models.PositiveIntegerField(default=2, help_text='Number of standard diss lines selectable per burn.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_line_selections',
            field=models.PositiveIntegerField(default=3, help_text='Total lines selectable per burn. Usually standard + premium. Diss = 3, Burn = 5 if premium lines count separately.'),
        ),
    ]
